---
title: "COVID19_Docentes_25-26, 44"
author: "CIDE"
date: "18/01/2020"
output: 
  word_document:
    reference_docx: plantilla.docx
---

```{r, echo=FALSE}
knitr::opts_chunk$set(warning=FALSE, echo = FALSE, fig.width=8, fig.height=6) 
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(readxl)
library(tidyverse)
library(knitr)
library(rlang)
encuesta <- read_xlsx("./encuesta.xlsx", col_names = T)
```
# 25
```{r}
encuesta %>%
  select(c(74:80)) %>%
  gather("Reactivo", "Percepción") %>%
  ggplot(aes(x = Reactivo, fill = Percepción)) +
  geom_bar(position = "fill") +
  geom_text(data = . %>% 
              group_by(Reactivo, Percepción) %>%
              tally() %>%
              mutate(prop = round(n / sum(n), 2)) %>%
              ungroup(), aes(y = prop, label = scales::percent(prop)), position = position_fill(vjust = 0.5), size = 3) +
  scale_y_continuous(breaks = c(0, 1), labels = scales::percent_format()) +
  scale_x_discrete(labels = c("TV", "Radio", "Temas\nTV", "Temas\nRadio", "Horarios", "Repetición\nTV", "Repetición\nRadio")) + 
  labs(title = 'Percepción de los docentes sobre los diferentes\naspectos de la estrategia "Aprende en casa"',
       x = "",
       y = "%")

X25 <- encuesta %>%
  select(c(74:80)) %>%
  gather("Reactivo", "Respuesta")
reactivo <- unique(X25$Reactivo)
respuesta <- unique(X25$Respuesta) %>% sort(.)

X25_frec <- as.data.frame(sapply(reactivo, function(i){
  reactivo_x <- X25 %>% filter(Reactivo == i)
  sapply(respuesta, function(j){
    opciones_x <- sum(reactivo_x == j)
  })
})) %>%
  rename(Cal.cont.TV = 1, Cal.cont.Radio = 2, 
         Conxn.cont.clases.TV = 3, Conxn.cont.clases.Radio = 4,
         Hor.abordan.temas = 5, Opc.rep.TV = 6,
         Opc.rep.Radio = 7)
kable(X25_frec)

kable(summarise_all(X25_frec, funs(round(./sum(.), 4))) %>% mutate(Percepción = respuesta) %>% select(8, 1:7))
```
#26
```{r}
encuesta %>%
  mutate(menos_dos_hrs = ifelse(X26_doc_hrs_clase < 2, 1, 0),
        dos_hrs = ifelse(X26_doc_hrs_clase == 2, 1, 0),
        tres_cuatro_hrs = ifelse(X26_doc_hrs_clase >= 3 & X26_doc_hrs_clase <= 4, 1, 0),
        cinco_seis_hrs = ifelse(X26_doc_hrs_clase >= 5 & X26_doc_hrs_clase <= 6, 1, 0),
        siete_ocho_hrs = ifelse(X26_doc_hrs_clase >= 7 & X26_doc_hrs_clase <= 8, 1, 0),
        mas_ocho_hrs = ifelse(X26_doc_hrs_clase > 8, 1, 0)) %>%
  select(c(168:173)) %>%
  gather("cat", "hrs") %>%
  filter(hrs != 0) %>%
  select(cat) %>%
  do(as.data.frame(table(.$cat))) %>%
  mutate(prop = round(Freq/3588, 2)) %>%
  ggplot(aes(x = prop, y = reorder(Var1, -prop), fill = Var1)) + 
  geom_bar(stat = "identity", show.legend = F) + 
  geom_text(aes(x = prop, label = scales::percent(prop)), position = position_nudge(x = 0.08), size = 3) + 
  scale_x_continuous(labels = scales::percent_format()) +
  scale_y_discrete(labels = c("Más de 8 hrs", "5 a 6 hrs", "7 a 8 hrs", 
                              "3 a 4 hrs", "2 hrs", "Menos de 2 hrs")) +
  labs(title = "Horas por semana que dedicaron los docentes\na la impartición de clases",
       x = "%",
       y = "")

kable(encuesta %>%
  mutate(menos_dos_hrs = ifelse(X26_doc_hrs_clase < 2, 1, 0),
        dos_hrs = ifelse(X26_doc_hrs_clase == 2, 1, 0),
        tres_cuatro_hrs = ifelse(X26_doc_hrs_clase >= 3 & X26_doc_hrs_clase <= 4, 1, 0),
        cinco_seis_hrs = ifelse(X26_doc_hrs_clase >= 5 & X26_doc_hrs_clase <= 6, 1, 0),
        siete_ocho_hrs = ifelse(X26_doc_hrs_clase >= 7 & X26_doc_hrs_clase <= 8, 1, 0),
        mas_ocho_hrs = ifelse(X26_doc_hrs_clase > 8, 1, 0)) %>%
  select(c(168:173)) %>%
  gather("cat", "hrs") %>%
  filter(hrs != 0) %>%
  select(cat) %>%
  do(as.data.frame(table(.$cat))) %>%
  mutate(Proporción = round(Freq/3588, 2)) %>%
  rename(Horas = Var1))

```
# 44
```{r}
encuesta %>%
  select(c(145:151)) %>%
  gather("Reactivo", "Percepción") %>%
  ggplot(aes(x = Reactivo, fill = Percepción)) +
  geom_bar(position = "fill") +
  geom_text(data = . %>%
              group_by(Reactivo, Percepción) %>%
              tally() %>%
              mutate(prop = round(n/sum(n), 2)) %>%
              ungroup(), aes(y = prop, label = scales::percent(prop)), position = position_fill(vjust = 0.5), size = 3) +
  scale_y_continuous(breaks = seq(0, 1, 0.1), labels = scales::percent_format()) +
  scale_x_discrete(labels = c("Programas de TV", "Youtube", "Redio", "Distribución\ncuadernillos\ntrabajo", "Sitio de\ninternet", "Educatel", "Correo\nelectrónico")) + 
  labs(title = 'Frecuencia de contacto de los alumnos hacia el docente\nsobre diferentes aspectos',
       x = "",
       y = "%")

X44 <- encuesta %>%
  select(c(145:151)) %>%
  gather("Reactivo", "Respuesta")
reactivo <- unique(X44$Reactivo)
respuesta <- unique(X44$Respuesta) %>% sort(.)

X44_frec <- as.data.frame(sapply(reactivo, function(i){
  reactivo_x <- X44 %>% filter(Reactivo == i)
  sapply(respuesta, function(j){
    opciones_x <- sum(reactivo_x == j)
  })
})) %>%
  rename(Acc.TV = 1, Acc.Youtube = 2, Acc.Radio = 3,
         Acc.cuad.trabajo = 4, Acc.sitio.intrnt = 5,
         Acc.educatel = 6, Acc.corr.elect = 7)
kable(X44_frec)

kable(summarise_all(X44_frec, funs(round(./sum(.), 4))) %>% mutate(Respuesta = c(respuesta)) %>% select(8, 1:7))
```